#!/bin/sh

GOPATH=${GOPATH:-~/go}

if [ ! -f $GOPATH/bin/chidley ]; then
    go get github.com/gnewton/chidley
fi

echo "/* This file has been autogenerated by tools/gen_xml_code.sh, please"
echo "   add more bugzillas to the list if you find any missing field"
echo "*/"
echo ""
echo "package bugzilla"
echo ""

$GOPATH/bin/chidley -t -G -u "https://bugzilla.redhat.com/show_bug.cgi?id=1525967&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=1503518&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=1433532&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=1548947&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=1433533&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=154891&ctype=xml" \
                          "https://bugzilla.redhat.com/show_bug.cgi?id=1532280&ctype=xml"| sed -e 's/string string/Content string/g'
