#!/bin/sh

GOPATH=${GOPATH:-~/go}

if [ ! -f $GOPATH/bin/chidley ]; then
    go get github.com/gnewton/chidley
fi

echo "/* This file has been autogenerated by tools/gen_xml_code.sh, please"
echo "   add more bugzillas to the list if you find any missing field"
echo "*/"
echo ""
echo "package bugzilla"
echo ""
echo "import \"encoding/xml\""

echo "" >/tmp/bz.xml

for bz in 1525967 1503518 1433532 1548947 1433533 154891 1498162 1532280; do
    curl "https://bugzilla.redhat.com/show_bug.cgi?id=$bz&ctype=xml" 2>/dev/null  >> /tmp/bz.xml
done

cat tools/bz.xml >>/tmp/bz.xml

$GOPATH/bin/chidley -t -G /tmp/bz.xml | sed -e 's/string string/Content string/g'
